"""004_correlations_system

Revision ID: 6cdf0b06a3e9
Revises: 2367184435ac
Create Date: 2025-10-25 21:27:28.088265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cdf0b06a3e9'
down_revision: Union[str, Sequence[str], None] = '2367184435ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False, comment='Unique name for this correlation rule'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of what this rule detects'),
    sa.Column('primary_event_type', sa.String(length=100), nullable=False, comment='Type of event that triggers correlation check: SOLAR_FLARE, EARTHQUAKE, NEO_APPROACH, etc.'),
    sa.Column('primary_threshold', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSONB conditions for primary event (e.g., {"class": "X", "magnitude": ">5.0"})'),
    sa.Column('secondary_event_type', sa.String(length=100), nullable=False, comment='Type of event to look for after primary: EARTHQUAKE, VOLCANIC, METEOR, etc.'),
    sa.Column('secondary_threshold', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSONB conditions for secondary event (e.g., {"magnitude": ">=7.5"})'),
    sa.Column('time_window_days', sa.Integer(), nullable=False, comment='Number of days to watch for secondary event after primary (1-365)'),
    sa.Column('minimum_confidence', sa.Float(), nullable=False, comment='Minimum confidence score (0.0-1.0) required to flag correlation'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Priority level 1-5 (1=highest)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this rule is currently active'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='When this rule was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='When this rule was last updated'),
    sa.CheckConstraint("primary_event_type IN ('SOLAR_FLARE', 'CME', 'GEOMAGNETIC_STORM', 'EARTHQUAKE', 'VOLCANIC', 'METEOR', 'NEO_APPROACH', 'IMPACT_RISK', 'LUNAR_ECLIPSE', 'SOLAR_ECLIPSE', 'COMET_PERIHELION', 'OTHER')", name='ck_primary_event_type'),
    sa.CheckConstraint("secondary_event_type IN ('SOLAR_FLARE', 'CME', 'GEOMAGNETIC_STORM', 'EARTHQUAKE', 'VOLCANIC', 'METEOR', 'NEO_APPROACH', 'IMPACT_RISK', 'LUNAR_ECLIPSE', 'SOLAR_ECLIPSE', 'COMET_PERIHELION', 'OTHER')", name='ck_secondary_event_type'),
    sa.CheckConstraint('minimum_confidence >= 0.0 AND minimum_confidence <= 1.0', name='ck_min_confidence'),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name='ck_corr_rule_priority'),
    sa.CheckConstraint('time_window_days >= 1 AND time_window_days <= 365', name='ck_time_window'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name'),
    comment='Rules for detecting correlations between different event types'
    )
    op.create_index('idx_correlation_rule_active', 'correlation_rules', ['is_active'], unique=False)
    op.create_index('idx_correlation_rule_primary_type', 'correlation_rules', ['primary_event_type'], unique=False)
    op.create_index('idx_correlation_rule_priority', 'correlation_rules', ['priority'], unique=False)
    op.create_index('idx_correlation_rule_secondary_type', 'correlation_rules', ['secondary_event_type'], unique=False)
    op.create_table('event_correlations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this correlation detection'),
    sa.Column('rule_id', sa.Integer(), nullable=True, comment='Reference to the correlation rule that detected this (NULL if rule deleted)'),
    sa.Column('primary_event_id', sa.UUID(), nullable=False, comment='UUID of the primary/trigger event'),
    sa.Column('primary_event_type', sa.String(length=100), nullable=False, comment='Type of primary event'),
    sa.Column('primary_event_time', sa.TIMESTAMP(timezone=True), nullable=False, comment='When the primary event occurred'),
    sa.Column('primary_event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSONB snapshot of primary event details'),
    sa.Column('secondary_event_id', sa.UUID(), nullable=False, comment='UUID of the secondary/consequent event'),
    sa.Column('secondary_event_type', sa.String(length=100), nullable=False, comment='Type of secondary event'),
    sa.Column('secondary_event_time', sa.TIMESTAMP(timezone=True), nullable=False, comment='When the secondary event occurred'),
    sa.Column('secondary_event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSONB snapshot of secondary event details'),
    sa.Column('time_delta_hours', sa.Float(), nullable=False, comment='Hours between primary and secondary events'),
    sa.Column('confidence_score', sa.Float(), nullable=False, comment='Confidence score 0.0-1.0 for this correlation'),
    sa.Column('spatial_distance_km', sa.Float(), nullable=True, comment='Distance in kilometers between events (if both have geographic coordinates)'),
    sa.Column('detected_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='When this correlation was detected'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes or context about this correlation'),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_confidence'),
    sa.CheckConstraint('spatial_distance_km >= 0.0 OR spatial_distance_km IS NULL', name='ck_spatial_distance'),
    sa.CheckConstraint('time_delta_hours >= 0.0', name='ck_time_delta'),
    sa.ForeignKeyConstraint(['rule_id'], ['correlation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Detected correlations between events with timing and confidence details'
    )
    op.create_index('idx_correlation_confidence', 'event_correlations', ['confidence_score'], unique=False)
    op.create_index('idx_correlation_detected_at', 'event_correlations', ['detected_at'], unique=False)
    op.create_index('idx_correlation_primary_event', 'event_correlations', ['primary_event_id'], unique=False)
    op.create_index('idx_correlation_primary_type', 'event_correlations', ['primary_event_type'], unique=False)
    op.create_index('idx_correlation_rule_id', 'event_correlations', ['rule_id'], unique=False)
    op.create_index('idx_correlation_secondary_event', 'event_correlations', ['secondary_event_id'], unique=False)
    op.create_index('idx_correlation_secondary_type', 'event_correlations', ['secondary_event_type'], unique=False)
    op.create_index('idx_correlation_time_delta', 'event_correlations', ['time_delta_hours'], unique=False)
    # NOTE: spatial_ref_sys is a PostGIS system table, don't drop it
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: spatial_ref_sys is a PostGIS system table, don't recreate it
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.drop_index('idx_correlation_time_delta', table_name='event_correlations')
    op.drop_index('idx_correlation_secondary_type', table_name='event_correlations')
    op.drop_index('idx_correlation_secondary_event', table_name='event_correlations')
    op.drop_index('idx_correlation_rule_id', table_name='event_correlations')
    op.drop_index('idx_correlation_primary_type', table_name='event_correlations')
    op.drop_index('idx_correlation_primary_event', table_name='event_correlations')
    op.drop_index('idx_correlation_detected_at', table_name='event_correlations')
    op.drop_index('idx_correlation_confidence', table_name='event_correlations')
    op.drop_table('event_correlations')
    op.drop_index('idx_correlation_rule_secondary_type', table_name='correlation_rules')
    op.drop_index('idx_correlation_rule_priority', table_name='correlation_rules')
    op.drop_index('idx_correlation_rule_primary_type', table_name='correlation_rules')
    op.drop_index('idx_correlation_rule_active', table_name='correlation_rules')
    op.drop_table('correlation_rules')
    # ### end Alembic commands ###
