"""006_add_volcanic_activity_table

Revision ID: 0a7fecbcd511
Revises: 7b8c9d0e1f23
Create Date: 2025-11-09 13:50:07.663412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7fecbcd511'
down_revision: Union[str, Sequence[str], None] = '7b8c9d0e1f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Volcanic Activity Table
    op.create_table('volcanic_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volcano_name', sa.String(length=255), nullable=False, comment='Name of the volcano'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Country or region'),
    sa.Column('eruption_start', sa.DateTime(), nullable=False, comment='Start time of eruption'),
    sa.Column('eruption_end', sa.DateTime(), nullable=True, comment='End time of eruption (null if ongoing)'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='Latitude in decimal degrees (-90 to 90)'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='Longitude in decimal degrees (-180 to 180)'),
    sa.Column('vei', sa.Integer(), nullable=True, comment='Volcanic Explosivity Index (0-8)'),
    sa.Column('eruption_type', sa.String(length=50), nullable=True, comment='Type: explosive, effusive, phreatic, etc.'),
    sa.Column('plume_height_km', sa.Float(), nullable=True, comment='Maximum plume height in kilometers'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional eruption details'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: Smithsonian GVP, VAAC, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('vei IS NULL OR (vei >= 0 AND vei <= 8)', name='ck_volcanic_vei_range'),
    sa.CheckConstraint('plume_height_km IS NULL OR plume_height_km >= 0', name='ck_volcanic_plume_nonnegative'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_volcanic_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_volcanic_longitude_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_volcanic_coordinates', 'volcanic_activity', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_volcanic_name', 'volcanic_activity', ['volcano_name'], unique=False)
    op.create_index('idx_volcanic_start', 'volcanic_activity', ['eruption_start'], unique=False)
    op.create_index('idx_volcanic_vei', 'volcanic_activity', ['vei'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_volcanic_vei', table_name='volcanic_activity')
    op.drop_index('idx_volcanic_start', table_name='volcanic_activity')
    op.drop_index('idx_volcanic_name', table_name='volcanic_activity')
    op.drop_index('idx_volcanic_coordinates', table_name='volcanic_activity')
    op.drop_table('volcanic_activity')
    # ### end Alembic commands ###
