"""001_initial_scientific_schema

Revision ID: 5fa859e69904
Revises: 
Create Date: 2025-10-25 20:56:10.968680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Removed geoalchemy2 - not available on Railway PostgreSQL


# revision identifiers, used by Alembic.
revision: str = '5fa859e69904'
down_revision: Union[str, Sequence[str], None] = None  # Requires PostGIS extension
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earthquakes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True, comment='External event ID (USGS, etc.)'),
    sa.Column('event_time', sa.DateTime(), nullable=False, comment='Time of earthquake occurrence'),
    sa.Column('magnitude', sa.Float(), nullable=False, comment='Earthquake magnitude'),
    sa.Column('magnitude_type', sa.String(length=10), nullable=True, comment='Type: Mw, ML, Ms, etc.'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='Latitude in decimal degrees (-90 to 90)'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='Longitude in decimal degrees (-180 to 180)'),
    sa.Column('depth_km', sa.Float(), nullable=True, comment='Depth below surface in kilometers'),
    sa.Column('region', sa.String(length=255), nullable=True, comment='Geographic region description'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: USGS, EMSC, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('depth_km IS NULL OR depth_km >= 0', name='ck_earthquake_depth_nonnegative'),
    sa.CheckConstraint('magnitude > 0', name='ck_earthquake_magnitude_positive'),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_earthquake_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_earthquake_longitude_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_earthquake_coordinates', 'earthquakes', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_earthquake_magnitude', 'earthquakes', ['magnitude'], unique=False)
    op.create_index('idx_earthquake_time', 'earthquakes', ['event_time'], unique=False)
    op.create_index(op.f('ix_earthquakes_event_id'), 'earthquakes', ['event_id'], unique=True)
    op.create_index(op.f('ix_earthquakes_event_time'), 'earthquakes', ['event_time'], unique=False)
    op.create_index(op.f('ix_earthquakes_magnitude'), 'earthquakes', ['magnitude'], unique=False)
    op.create_table('ephemeris_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False, comment='Name or designation of the celestial object'),
    sa.Column('object_type', sa.String(length=50), nullable=False, comment='Type: asteroid, comet, planet, etc.'),
    sa.Column('epoch_iso', sa.DateTime(), nullable=False, comment='ISO 8601 timestamp of observation'),
    sa.Column('x_au', sa.Float(), nullable=False, comment='X coordinate in Astronomical Units'),
    sa.Column('y_au', sa.Float(), nullable=False, comment='Y coordinate in Astronomical Units'),
    sa.Column('z_au', sa.Float(), nullable=False, comment='Z coordinate in Astronomical Units'),
    sa.Column('vx_au_day', sa.Float(), nullable=True, comment='X velocity component in AU/day'),
    sa.Column('vy_au_day', sa.Float(), nullable=True, comment='Y velocity component in AU/day'),
    sa.Column('vz_au_day', sa.Float(), nullable=True, comment='Z velocity component in AU/day'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: JPL, MPC, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_name', 'epoch_iso', name='uq_ephemeris_object_epoch')
    )
    op.create_index('idx_ephemeris_object_epoch', 'ephemeris_data', ['object_name', 'epoch_iso'], unique=False)
    op.create_index('idx_ephemeris_type', 'ephemeris_data', ['object_type'], unique=False)
    op.create_index(op.f('ix_ephemeris_data_epoch_iso'), 'ephemeris_data', ['epoch_iso'], unique=False)
    op.create_index(op.f('ix_ephemeris_data_object_name'), 'ephemeris_data', ['object_name'], unique=False)
    op.create_table('impact_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False, comment='Name or designation of the NEO'),
    sa.Column('impact_date', sa.DateTime(), nullable=False, comment='Potential impact date'),
    sa.Column('impact_probability', sa.Float(), nullable=False, comment='Impact probability (0.0 to 1.0)'),
    sa.Column('palermo_scale', sa.Float(), nullable=True, comment='Palermo Technical Impact Hazard Scale value'),
    sa.Column('torino_scale', sa.Integer(), nullable=True, comment='Torino Scale value (0-10)'),
    sa.Column('estimated_diameter_m', sa.Float(), nullable=True, comment='Estimated object diameter in meters'),
    sa.Column('impact_energy_mt', sa.Float(), nullable=True, comment='Estimated impact energy in megatons TNT'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: NASA Sentry, ESA NEOCC, etc.'),
    sa.Column('assessment_date', sa.DateTime(), nullable=False, comment='When this assessment was made'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('impact_probability >= 0 AND impact_probability <= 1', name='ck_impact_probability_range'),
    sa.CheckConstraint('torino_scale IS NULL OR (torino_scale >= 0 AND torino_scale <= 10)', name='ck_torino_scale_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_impact_risk_date', 'impact_risks', ['impact_date'], unique=False)
    op.create_index('idx_impact_risk_probability', 'impact_risks', ['impact_probability'], unique=False)
    op.create_index('idx_impact_risk_torino', 'impact_risks', ['torino_scale'], unique=False)
    op.create_index(op.f('ix_impact_risks_impact_date'), 'impact_risks', ['impact_date'], unique=False)
    op.create_index(op.f('ix_impact_risks_object_name'), 'impact_risks', ['object_name'], unique=False)
    op.create_table('meteor_showers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shower_name', sa.String(length=100), nullable=False, comment='Official meteor shower name'),
    sa.Column('iau_code', sa.String(length=10), nullable=True, comment='IAU three-letter code'),
    sa.Column('peak_month', sa.Integer(), nullable=False, comment='Peak month (1-12)'),
    sa.Column('peak_day_start', sa.Integer(), nullable=False, comment='Start day of peak period'),
    sa.Column('peak_day_end', sa.Integer(), nullable=False, comment='End day of peak period'),
    sa.Column('radiant_ra_deg', sa.Float(), nullable=True, comment='Right ascension of radiant in degrees (J2000)'),
    sa.Column('radiant_dec_deg', sa.Float(), nullable=True, comment='Declination of radiant in degrees (J2000)'),
    sa.Column('zhr_max', sa.Integer(), nullable=True, comment='Maximum Zenithal Hourly Rate'),
    sa.Column('velocity_km_s', sa.Float(), nullable=True, comment='Entry velocity in km/s'),
    sa.Column('parent_body', sa.String(length=100), nullable=True, comment='Associated comet or asteroid'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('peak_day_end >= 1 AND peak_day_end <= 31', name='ck_meteor_day_end_range'),
    sa.CheckConstraint('peak_day_start >= 1 AND peak_day_start <= 31', name='ck_meteor_day_start_range'),
    sa.CheckConstraint('peak_month >= 1 AND peak_month <= 12', name='ck_meteor_month_range'),
    sa.CheckConstraint('radiant_dec_deg IS NULL OR (radiant_dec_deg >= -90 AND radiant_dec_deg <= 90)', name='ck_meteor_dec_range'),
    sa.CheckConstraint('radiant_ra_deg IS NULL OR (radiant_ra_deg >= 0 AND radiant_ra_deg < 360)', name='ck_meteor_ra_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iau_code')
    )
    op.create_index('idx_meteor_peak_month', 'meteor_showers', ['peak_month'], unique=False)
    op.create_index('idx_meteor_shower_name', 'meteor_showers', ['shower_name'], unique=False)
    op.create_index(op.f('ix_meteor_showers_shower_name'), 'meteor_showers', ['shower_name'], unique=True)
    op.create_table('neo_close_approaches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False, comment='Name or designation of the NEO'),
    sa.Column('approach_date', sa.DateTime(), nullable=False, comment='Date and time of closest approach'),
    sa.Column('miss_distance_au', sa.Float(), nullable=False, comment='Miss distance in Astronomical Units'),
    sa.Column('miss_distance_lunar', sa.Float(), nullable=True, comment='Miss distance in lunar distances (LD)'),
    sa.Column('relative_velocity_km_s', sa.Float(), nullable=True, comment='Relative velocity in km/s'),
    sa.Column('estimated_diameter_m', sa.Float(), nullable=True, comment='Estimated object diameter in meters'),
    sa.Column('absolute_magnitude', sa.Float(), nullable=True, comment='Absolute magnitude (H)'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: JPL SBDB, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('miss_distance_au > 0', name='ck_neo_distance_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_neo_approach_date', 'neo_close_approaches', ['approach_date'], unique=False)
    op.create_index('idx_neo_approach_distance', 'neo_close_approaches', ['miss_distance_au'], unique=False)
    op.create_index(op.f('ix_neo_close_approaches_approach_date'), 'neo_close_approaches', ['approach_date'], unique=False)
    op.create_index(op.f('ix_neo_close_approaches_object_name'), 'neo_close_approaches', ['object_name'], unique=False)
    op.create_table('orbital_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=False, comment='Name or designation of the celestial object'),
    sa.Column('epoch_iso', sa.DateTime(), nullable=False, comment='Reference epoch for orbital elements'),
    sa.Column('semi_major_axis_au', sa.Float(), nullable=False, comment='Semi-major axis in AU'),
    sa.Column('eccentricity', sa.Float(), nullable=False, comment='Orbital eccentricity (0 = circle, <1 = ellipse, >=1 = hyperbola)'),
    sa.Column('inclination_deg', sa.Float(), nullable=False, comment='Orbital inclination in degrees'),
    sa.Column('longitude_ascending_node_deg', sa.Float(), nullable=False, comment='Longitude of ascending node in degrees'),
    sa.Column('argument_perihelion_deg', sa.Float(), nullable=False, comment='Argument of perihelion in degrees'),
    sa.Column('mean_anomaly_deg', sa.Float(), nullable=False, comment='Mean anomaly at epoch in degrees'),
    sa.Column('is_interstellar', sa.Boolean(), sa.Computed('(eccentricity >= 1.0)', ), nullable=True, comment='True if eccentricity >= 1.0 (hyperbolic orbit)'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: JPL, MPC, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('eccentricity >= 0', name='ck_orbital_eccentricity_positive'),
    sa.CheckConstraint('inclination_deg >= 0 AND inclination_deg <= 180', name='ck_orbital_inclination_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_name', 'epoch_iso', name='uq_orbital_object_epoch')
    )
    op.create_index('idx_orbital_interstellar', 'orbital_elements', ['is_interstellar'], unique=False)
    op.create_index('idx_orbital_object', 'orbital_elements', ['object_name'], unique=False)
    op.create_index(op.f('ix_orbital_elements_object_name'), 'orbital_elements', ['object_name'], unique=False)
    op.create_table('solar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='Type: solar_flare, cme, geomagnetic_storm'),
    sa.Column('event_start', sa.DateTime(), nullable=False, comment='Start time of solar event'),
    sa.Column('event_end', sa.DateTime(), nullable=True, comment='End time of solar event'),
    sa.Column('flare_class', sa.String(length=10), nullable=True, comment='X-ray class: A, B, C, M, X'),
    sa.Column('flare_region', sa.String(length=50), nullable=True, comment='Active region number'),
    sa.Column('cme_speed_km_s', sa.Float(), nullable=True, comment='CME speed in km/s'),
    sa.Column('cme_angle_deg', sa.Float(), nullable=True, comment='CME angular width in degrees'),
    sa.Column('kp_index', sa.Float(), nullable=True, comment='Planetary K-index (0-9)'),
    sa.Column('dst_index_nt', sa.Float(), nullable=True, comment='Disturbance Storm Time index in nT'),
    sa.Column('earth_arrival_time', sa.DateTime(), nullable=True, comment='Predicted/actual Earth arrival time'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional event details'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: NOAA SWPC, NASA, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("event_type IN ('solar_flare', 'cme', 'geomagnetic_storm')", name='ck_solar_event_type'),
    sa.CheckConstraint('kp_index IS NULL OR (kp_index >= 0 AND kp_index <= 9)', name='ck_kp_index_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_solar_event_start', 'solar_events', ['event_start'], unique=False)
    op.create_index('idx_solar_event_type', 'solar_events', ['event_type'], unique=False)
    op.create_index('idx_solar_kp_index', 'solar_events', ['kp_index'], unique=False)
    op.create_index(op.f('ix_solar_events_event_start'), 'solar_events', ['event_start'], unique=False)
    op.create_index(op.f('ix_solar_events_event_type'), 'solar_events', ['event_type'], unique=False)
    op.create_table('volcanic_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volcano_name', sa.String(length=255), nullable=False, comment='Name of the volcano'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='Country or region'),
    sa.Column('eruption_start', sa.DateTime(), nullable=False, comment='Start time of eruption'),
    sa.Column('eruption_end', sa.DateTime(), nullable=True, comment='End time of eruption (null if ongoing)'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='Latitude in decimal degrees (-90 to 90)'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='Longitude in decimal degrees (-180 to 180)'),
    sa.Column('vei', sa.Integer(), nullable=True, comment='Volcanic Explosivity Index (0-8)'),
    sa.Column('eruption_type', sa.String(length=50), nullable=True, comment='Type: explosive, effusive, phreatic, etc.'),
    sa.Column('plume_height_km', sa.Float(), nullable=True, comment='Maximum plume height in kilometers'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional eruption details'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: Smithsonian GVP, VAAC, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_volcanic_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_volcanic_longitude_range'),
    sa.CheckConstraint('plume_height_km IS NULL OR plume_height_km >= 0', name='ck_volcanic_plume_nonnegative'),
    sa.CheckConstraint('vei IS NULL OR (vei >= 0 AND vei <= 8)', name='ck_volcanic_vei_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_volcanic_coordinates', 'volcanic_activity', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_volcanic_name', 'volcanic_activity', ['volcano_name'], unique=False)
    op.create_index('idx_volcanic_start', 'volcanic_activity', ['eruption_start'], unique=False)
    op.create_index('idx_volcanic_vei', 'volcanic_activity', ['vei'], unique=False)
    op.create_index(op.f('ix_volcanic_activity_eruption_start'), 'volcanic_activity', ['eruption_start'], unique=False)
    op.create_index(op.f('ix_volcanic_activity_vei'), 'volcanic_activity', ['vei'], unique=False)
    op.create_index(op.f('ix_volcanic_activity_volcano_name'), 'volcanic_activity', ['volcano_name'], unique=False)
    # spatial_ref_sys is a PostGIS system table - do not drop
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # spatial_ref_sys is a PostGIS system table - do not recreate
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    # sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    # )
    op.drop_index(op.f('ix_volcanic_activity_volcano_name'), table_name='volcanic_activity')
    op.drop_index(op.f('ix_volcanic_activity_vei'), table_name='volcanic_activity')
    op.drop_index(op.f('ix_volcanic_activity_eruption_start'), table_name='volcanic_activity')
    op.drop_index('idx_volcanic_vei', table_name='volcanic_activity')
    op.drop_index('idx_volcanic_start', table_name='volcanic_activity')
    op.drop_index('idx_volcanic_name', table_name='volcanic_activity')
    op.drop_index('idx_volcanic_coordinates', table_name='volcanic_activity')
    op.drop_table('volcanic_activity')
    op.drop_index(op.f('ix_solar_events_event_type'), table_name='solar_events')
    op.drop_index(op.f('ix_solar_events_event_start'), table_name='solar_events')
    op.drop_index('idx_solar_kp_index', table_name='solar_events')
    op.drop_index('idx_solar_event_type', table_name='solar_events')
    op.drop_index('idx_solar_event_start', table_name='solar_events')
    op.drop_table('solar_events')
    op.drop_index(op.f('ix_orbital_elements_object_name'), table_name='orbital_elements')
    op.drop_index('idx_orbital_object', table_name='orbital_elements')
    op.drop_index('idx_orbital_interstellar', table_name='orbital_elements')
    op.drop_table('orbital_elements')
    op.drop_index(op.f('ix_neo_close_approaches_object_name'), table_name='neo_close_approaches')
    op.drop_index(op.f('ix_neo_close_approaches_approach_date'), table_name='neo_close_approaches')
    op.drop_index('idx_neo_approach_distance', table_name='neo_close_approaches')
    op.drop_index('idx_neo_approach_date', table_name='neo_close_approaches')
    op.drop_table('neo_close_approaches')
    op.drop_index(op.f('ix_meteor_showers_shower_name'), table_name='meteor_showers')
    op.drop_index('idx_meteor_shower_name', table_name='meteor_showers')
    op.drop_index('idx_meteor_peak_month', table_name='meteor_showers')
    op.drop_table('meteor_showers')
    op.drop_index(op.f('ix_impact_risks_object_name'), table_name='impact_risks')
    op.drop_index(op.f('ix_impact_risks_impact_date'), table_name='impact_risks')
    op.drop_index('idx_impact_risk_torino', table_name='impact_risks')
    op.drop_index('idx_impact_risk_probability', table_name='impact_risks')
    op.drop_index('idx_impact_risk_date', table_name='impact_risks')
    op.drop_table('impact_risks')
    op.drop_index(op.f('ix_ephemeris_data_object_name'), table_name='ephemeris_data')
    op.drop_index(op.f('ix_ephemeris_data_epoch_iso'), table_name='ephemeris_data')
    op.drop_index('idx_ephemeris_type', table_name='ephemeris_data')
    op.drop_index('idx_ephemeris_object_epoch', table_name='ephemeris_data')
    op.drop_table('ephemeris_data')
    op.drop_index(op.f('ix_earthquakes_magnitude'), table_name='earthquakes')
    op.drop_index(op.f('ix_earthquakes_event_time'), table_name='earthquakes')
    op.drop_index(op.f('ix_earthquakes_event_id'), table_name='earthquakes')
    op.drop_index('idx_earthquake_time', table_name='earthquakes')
    op.drop_index('idx_earthquake_magnitude', table_name='earthquakes')
    op.drop_index('idx_earthquake_coordinates', table_name='earthquakes')
    op.drop_table('earthquakes')
    # ### end Alembic commands ###
