"""005_seismos_natural_disasters

Add hurricanes and tsunamis tables for comprehensive seismos (σεισμός) tracking.
Greek seismos = "commotion of air and ground" (Matthew 24:7, Revelation 6:12)

Revision ID: 7b8c9d0e1f23
Revises: 6cdf0b06a3e9
Create Date: 2025-11-08 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Removed geoalchemy2 - not available on Railway PostgreSQL


# revision identifiers, used by Alembic.
revision: str = '7b8c9d0e1f23'
down_revision: Union[str, None] = '6cdf0b06a3e9'  # Changed from 2367184435ac to fix branched migrations
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Hurricanes/Cyclones/Typhoons Table
    op.create_table('hurricanes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storm_name', sa.String(length=255), nullable=False, comment='Hurricane name (e.g., Katrina, Ian)'),
    sa.Column('basin', sa.String(length=50), nullable=False, comment='Ocean basin: Atlantic, East Pacific, West Pacific, Indian, etc.'),
    sa.Column('storm_type', sa.String(length=50), nullable=False, comment='Hurricane, Typhoon, Cyclone, Tropical Storm'),
    sa.Column('season', sa.Integer(), nullable=False, comment='Hurricane season year'),
    sa.Column('formation_date', sa.DateTime(), nullable=False, comment='Storm formation timestamp'),
    sa.Column('dissipation_date', sa.DateTime(), nullable=True, comment='Storm dissipation timestamp (null if ongoing)'),
    sa.Column('peak_latitude', sa.Float(), nullable=False, comment='Latitude of peak intensity in decimal degrees (-90 to 90)'),
    sa.Column('peak_longitude', sa.Float(), nullable=False, comment='Longitude of peak intensity in decimal degrees (-180 to 180)'),
    sa.Column('max_sustained_winds_kph', sa.Float(), nullable=True, comment='Maximum sustained winds in km/h'),
    sa.Column('min_central_pressure_hpa', sa.Float(), nullable=True, comment='Minimum central pressure in hectopascals'),
    sa.Column('category', sa.Integer(), nullable=True, comment='Saffir-Simpson scale (1-5) or equivalent'),
    sa.Column('ace_index', sa.Float(), nullable=True, comment='Accumulated Cyclone Energy index'),
    sa.Column('fatalities', sa.Integer(), nullable=True, comment='Total number of fatalities'),
    sa.Column('damages_usd_millions', sa.Float(), nullable=True, comment='Economic damages in millions USD'),
    sa.Column('affected_regions', sa.ARRAY(sa.String()), nullable=True, comment='List of affected countries/regions'),
    sa.Column('landfall_locations', sa.ARRAY(sa.String()), nullable=True, comment='Cities/regions where landfall occurred'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional storm details'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: NOAA NHC, JTWC, JMA, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('peak_latitude >= -90 AND peak_latitude <= 90', name='ck_hurricane_latitude_range'),
    sa.CheckConstraint('peak_longitude >= -180 AND peak_longitude <= 180', name='ck_hurricane_longitude_range'),
    sa.CheckConstraint('max_sustained_winds_kph IS NULL OR max_sustained_winds_kph >= 0', name='ck_hurricane_winds_nonnegative'),
    sa.CheckConstraint('min_central_pressure_hpa IS NULL OR min_central_pressure_hpa > 0', name='ck_hurricane_pressure_positive'),
    sa.CheckConstraint('category IS NULL OR (category >= 1 AND category <= 5)', name='ck_hurricane_category_range'),
    sa.CheckConstraint('fatalities IS NULL OR fatalities >= 0', name='ck_hurricane_fatalities_nonnegative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hurricane_coordinates', 'hurricanes', ['peak_latitude', 'peak_longitude'], unique=False)
    op.create_index('idx_hurricane_name', 'hurricanes', ['storm_name'], unique=False)
    op.create_index('idx_hurricane_formation', 'hurricanes', ['formation_date'], unique=False)
    op.create_index('idx_hurricane_category', 'hurricanes', ['category'], unique=False)
    op.create_index('idx_hurricane_season', 'hurricanes', ['season'], unique=False)
    op.create_index(op.f('ix_hurricanes_formation_date'), 'hurricanes', ['formation_date'], unique=False)
    op.create_index(op.f('ix_hurricanes_storm_name'), 'hurricanes', ['storm_name'], unique=False)
    
    # Tsunamis Table
    op.create_table('tsunamis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False, comment='Tsunami event timestamp'),
    sa.Column('source_latitude', sa.Float(), nullable=False, comment='Tsunami source latitude in decimal degrees (-90 to 90)'),
    sa.Column('source_longitude', sa.Float(), nullable=False, comment='Tsunami source longitude in decimal degrees (-180 to 180)'),
    sa.Column('source_type', sa.String(length=100), nullable=False, comment='Earthquake, Volcanic, Landslide, Meteorite, Unknown'),
    sa.Column('earthquake_magnitude', sa.Float(), nullable=True, comment='Related earthquake magnitude (if applicable)'),
    sa.Column('max_wave_height_m', sa.Float(), nullable=True, comment='Maximum recorded wave height in meters'),
    sa.Column('max_runup_m', sa.Float(), nullable=True, comment='Maximum runup elevation in meters'),
    sa.Column('affected_regions', sa.ARRAY(sa.String()), nullable=True, comment='List of affected coastlines/countries'),
    sa.Column('fatalities', sa.Integer(), nullable=True, comment='Total number of fatalities'),
    sa.Column('damages_usd_millions', sa.Float(), nullable=True, comment='Economic damages in millions USD'),
    sa.Column('intensity_scale', sa.Integer(), nullable=True, comment='Tsunami intensity (0-12 Soloviev-Imamura scale)'),
    sa.Column('travel_time_minutes', sa.Integer(), nullable=True, comment='Time from source to first landfall (minutes)'),
    sa.Column('warning_issued', sa.Boolean(), nullable=True, comment='Was a warning issued before impact?'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional tsunami details'),
    sa.Column('data_source', sa.String(length=100), nullable=True, comment='Source: NOAA NGDC, PTWC, JMA, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('source_latitude >= -90 AND source_latitude <= 90', name='ck_tsunami_latitude_range'),
    sa.CheckConstraint('source_longitude >= -180 AND source_longitude <= 180', name='ck_tsunami_longitude_range'),
    sa.CheckConstraint('max_wave_height_m IS NULL OR max_wave_height_m >= 0', name='ck_tsunami_wave_height_nonnegative'),
    sa.CheckConstraint('max_runup_m IS NULL OR max_runup_m >= 0', name='ck_tsunami_runup_nonnegative'),
    sa.CheckConstraint('intensity_scale IS NULL OR (intensity_scale >= 0 AND intensity_scale <= 12)', name='ck_tsunami_intensity_range'),
    sa.CheckConstraint('fatalities IS NULL OR fatalities >= 0', name='ck_tsunami_fatalities_nonnegative'),
    sa.CheckConstraint("source_type IN ('EARTHQUAKE', 'VOLCANIC', 'LANDSLIDE', 'METEORITE', 'UNKNOWN')", name='ck_tsunami_source_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tsunami_coordinates', 'tsunamis', ['source_latitude', 'source_longitude'], unique=False)
    op.create_index('idx_tsunami_date', 'tsunamis', ['event_date'], unique=False)
    op.create_index('idx_tsunami_source', 'tsunamis', ['source_type'], unique=False)
    op.create_index('idx_tsunami_intensity', 'tsunamis', ['intensity_scale'], unique=False)
    op.create_index(op.f('ix_tsunamis_event_date'), 'tsunamis', ['event_date'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tsunamis_event_date'), table_name='tsunamis')
    op.drop_index('idx_tsunami_intensity', table_name='tsunamis')
    op.drop_index('idx_tsunami_source', table_name='tsunamis')
    op.drop_index('idx_tsunami_date', table_name='tsunamis')
    op.drop_index('idx_tsunami_coordinates', table_name='tsunamis')
    op.drop_table('tsunamis')
    
    op.drop_index(op.f('ix_hurricanes_storm_name'), table_name='hurricanes')
    op.drop_index(op.f('ix_hurricanes_formation_date'), table_name='hurricanes')
    op.drop_index('idx_hurricane_season', table_name='hurricanes')
    op.drop_index('idx_hurricane_category', table_name='hurricanes')
    op.drop_index('idx_hurricane_formation', table_name='hurricanes')
    op.drop_index('idx_hurricane_name', table_name='hurricanes')
    op.drop_index('idx_hurricane_coordinates', table_name='hurricanes')
    op.drop_table('hurricanes')
    # ### end Alembic commands ###
