"""003_alerts_system

Revision ID: 2367184435ac
Revises: 4e4fe003d573
Create Date: 2025-10-25 21:20:35.486320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2367184435ac'
down_revision: Union[str, Sequence[str], None] = '4e4fe003d573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_triggers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sign_id', sa.Integer(), nullable=False, comment='Reference to celestial_signs table'),
    sa.Column('trigger_name', sa.String(length=255), nullable=False, comment="Descriptive name of the trigger (e.g., 'Wormwood - High Impact Risk')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of what this trigger watches for'),
    sa.Column('data_source_api', sa.String(length=100), nullable=False, comment='API/table to query: JPL_HORIZONS, JPL_SENTRY, USGS_EARTHQUAKE, NOAA_SWPC, etc.'),
    sa.Column('query_parameter', sa.String(length=100), nullable=False, comment="Field to check (e.g., 'torino_scale_max', 'magnitude', 'object_name')"),
    sa.Column('query_operator', sa.String(length=20), nullable=False, comment='Comparison operator: =, !=, >, <, >=, <=, CONTAINS, IN, BETWEEN'),
    sa.Column('query_value', sa.String(length=255), nullable=False, comment="Value to compare against (e.g., '0', '8.0', 'wormwood')"),
    sa.Column('additional_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Complex nested conditions as JSON (e.g., {'secondary_check': 'palermo_scale > -2', 'logic': 'AND'})"),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Priority level: 1=High, 2=Medium-High, 3=Medium, 4=Medium-Low, 5=Low'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this trigger is currently active and monitoring'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='When this trigger was created'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When this trigger was last modified'),
    sa.CheckConstraint("data_source_api IN ('JPL_HORIZONS', 'JPL_SENTRY', 'JPL_CNEOS', 'USGS_EARTHQUAKE', 'NOAA_SWPC', 'SMITHSONIAN_VOLCANO', 'GLOBAL_METEOR_NETWORK', 'IMO_METEOR', 'NASA_NEO', 'OTHER')", name='ck_data_source_api'),
    sa.CheckConstraint("query_operator IN ('=', '!=', '>', '<', '>=', '<=', 'CONTAINS', 'NOT_CONTAINS', 'IN', 'NOT_IN', 'BETWEEN', 'LIKE', 'ILIKE')", name='ck_query_operator'),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name='ck_trigger_priority'),
    sa.ForeignKeyConstraint(['sign_id'], ['celestial_signs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Configurable alert trigger rules (Prophetic Data Signatures)'
    )
    op.create_index('idx_trigger_active', 'data_triggers', ['is_active'], unique=False)
    op.create_index('idx_trigger_priority', 'data_triggers', ['priority'], unique=False)
    op.create_index('idx_trigger_sign', 'data_triggers', ['sign_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=True, comment='Reference to data_triggers table (NULL for manual alerts)'),
    sa.Column('alert_type', sa.String(length=100), nullable=False, comment='Type: IMPACT_RISK, CLOSE_APPROACH, EARTHQUAKE, SOLAR_FLARE, VOLCANIC_ERUPTION, etc.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment="Brief alert title (e.g., 'Apophis High Impact Risk Alert')"),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of the alert and why it was triggered'),
    sa.Column('related_object_name', sa.String(length=255), nullable=True, comment="Name of celestial object or location (e.g., 'Apophis', 'San Francisco')"),
    sa.Column('related_event_id', sa.UUID(), nullable=True, comment='UUID of the source event record (ephemeris_data.id, earthquakes.id, etc.)'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severity level: LOW, MEDIUM, HIGH, CRITICAL'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Alert status: ACTIVE, ACKNOWLEDGED, RESOLVED, DISMISSED'),
    sa.Column('triggered_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='When the alert was first triggered'),
    sa.Column('acknowledged_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When the alert was acknowledged by a user'),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='When the alert was resolved or dismissed'),
    sa.Column('trigger_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Complete snapshot of trigger conditions and event data that caused this alert'),
    sa.Column('resolution_notes', sa.Text(), nullable=True, comment='Notes about how the alert was resolved or why it was dismissed'),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True, comment='User who acknowledged the alert'),
    sa.Column('resolved_by', sa.String(length=100), nullable=True, comment='User who resolved the alert'),
    sa.CheckConstraint("alert_type IN ('IMPACT_RISK', 'CLOSE_APPROACH', 'EARTHQUAKE', 'SOLAR_FLARE', 'GEOMAGNETIC_STORM', 'VOLCANIC_ERUPTION', 'METEOR_SHOWER', 'COMET_PERIHELION', 'INTERSTELLAR_OBJECT', 'PROPHETIC_SIGN', 'OTHER')", name='ck_alert_type'),
    sa.CheckConstraint("severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')", name='ck_alert_severity'),
    sa.CheckConstraint("status IN ('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED')", name='ck_alert_status'),
    sa.ForeignKeyConstraint(['trigger_id'], ['data_triggers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Generated alerts with severity levels and lifecycle tracking'
    )
    op.create_index('idx_alert_object', 'alerts', ['related_object_name'], unique=False)
    op.create_index('idx_alert_severity', 'alerts', ['severity'], unique=False)
    op.create_index('idx_alert_status', 'alerts', ['status'], unique=False)
    op.create_index('idx_alert_triggered', 'alerts', ['triggered_at'], unique=False)
    op.create_index('idx_alert_type', 'alerts', ['alert_type'], unique=False)
    # Note: spatial_ref_sys is a PostGIS system table, not dropping it
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: spatial_ref_sys is a PostGIS system table, not recreating it
    # op.create_table('spatial_ref_sys', ...)
    op.drop_index('idx_alert_type', table_name='alerts')
    op.drop_index('idx_alert_triggered', table_name='alerts')
    op.drop_index('idx_alert_status', table_name='alerts')
    op.drop_index('idx_alert_severity', table_name='alerts')
    op.drop_index('idx_alert_object', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_trigger_sign', table_name='data_triggers')
    op.drop_index('idx_trigger_priority', table_name='data_triggers')
    op.drop_index('idx_trigger_active', table_name='data_triggers')
    op.drop_table('data_triggers')
    # ### end Alembic commands ###
