"""002_theological_schema

Revision ID: 4e4fe003d573
Revises: 5fa859e69904
Create Date: 2025-10-25 21:07:54.990806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e4fe003d573'
down_revision: Union[str, Sequence[str], None] = '5fa859e69904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celestial_signs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sign_name', sa.String(length=255), nullable=False, comment="Unique name of the celestial sign (e.g., 'Great Earthquake', 'Blood Moon')"),
    sa.Column('sign_description', sa.Text(), nullable=False, comment='Physical description of the sign as recorded in scripture'),
    sa.Column('theological_interpretation', sa.Text(), nullable=False, comment='Theological meaning and significance of the sign'),
    sa.Column('primary_scripture', sa.String(length=255), nullable=False, comment="Main scripture reference for this sign (e.g., 'Revelation 6:12')"),
    sa.Column('related_scriptures', sa.ARRAY(sa.String()), nullable=True, comment='Array of additional scripture references that mention this sign'),
    sa.Column('sign_type', sa.String(length=100), nullable=True, comment='Type: COSMIC, TERRESTRIAL, ATMOSPHERIC, SOLAR, LUNAR, STELLAR, SEISMIC, VOLCANIC'),
    sa.CheckConstraint("sign_type IN ('COSMIC', 'TERRESTRIAL', 'ATMOSPHERIC', 'SOLAR', 'LUNAR', 'STELLAR', 'SEISMIC', 'VOLCANIC', 'COMBINED', 'OTHER') OR sign_type IS NULL", name='ck_sign_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sign_name'),
    comment='Celestial signs with theological interpretations and scripture references'
    )
    op.create_index('idx_sign_name', 'celestial_signs', ['sign_name'], unique=False)
    op.create_index('idx_sign_type', 'celestial_signs', ['sign_type'], unique=False)
    op.create_table('prophecies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False, comment="Name of prophetic event (e.g., 'Sixth Seal Judgment')"),
    sa.Column('scripture_reference', sa.String(length=255), nullable=False, comment="Bible reference (e.g., 'Revelation 6:12-14')"),
    sa.Column('scripture_text', sa.Text(), nullable=False, comment='Full text of the prophecy passage'),
    sa.Column('event_description', sa.Text(), nullable=True, comment='Description of the prophetic events'),
    sa.Column('prophecy_category', sa.String(length=100), nullable=False, comment='Category: SEAL_JUDGMENT, TRUMPET_JUDGMENT, BOWL_JUDGMENT, DAY_OF_LORD, SECOND_COMING, etc.'),
    sa.Column('chronological_order', sa.Integer(), nullable=True, comment='Sequential order within a category (e.g., Seal 1-7, Trumpet 1-7)'),
    sa.Column('theological_notes', sa.Text(), nullable=True, comment='Additional theological context or interpretive notes'),
    sa.CheckConstraint("prophecy_category IN ('SEAL_JUDGMENT', 'TRUMPET_JUDGMENT', 'BOWL_JUDGMENT', 'DAY_OF_LORD', 'SECOND_COMING', 'TRIBULATION', 'MILLENNIAL_REIGN', 'COSMIC_DISTURBANCE', 'OTHER')", name='ck_prophecy_category'),
    sa.PrimaryKeyConstraint('id'),
    comment='Biblical prophecies with scripture references and theological categorization'
    )
    op.create_index('idx_prophecy_category', 'prophecies', ['prophecy_category'], unique=False)
    op.create_index('idx_prophecy_order', 'prophecies', ['chronological_order'], unique=False)
    op.create_table('prophecy_sign_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prophecy_id', sa.Integer(), nullable=False, comment='Reference to prophecies table'),
    sa.Column('sign_id', sa.Integer(), nullable=False, comment='Reference to celestial_signs table'),
    sa.Column('link_notes', sa.Text(), nullable=True, comment='Optional notes about this specific prophecy-sign relationship'),
    sa.ForeignKeyConstraint(['prophecy_id'], ['prophecies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sign_id'], ['celestial_signs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prophecy_id', 'sign_id', name='uq_prophecy_sign'),
    comment='Many-to-many junction table linking prophecies to celestial signs'
    )
    op.create_index('idx_prop_sign_prophecy', 'prophecy_sign_links', ['prophecy_id'], unique=False)
    op.create_index('idx_prop_sign_sign', 'prophecy_sign_links', ['sign_id'], unique=False)
    # Note: spatial_ref_sys is a PostGIS system table, not dropping it
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: spatial_ref_sys is a PostGIS system table, not recreating it
    # op.create_table('spatial_ref_sys', ...)
    op.drop_index('idx_prop_sign_sign', table_name='prophecy_sign_links')
    op.drop_index('idx_prop_sign_prophecy', table_name='prophecy_sign_links')
    op.drop_table('prophecy_sign_links')
    op.drop_index('idx_prophecy_order', table_name='prophecies')
    op.drop_index('idx_prophecy_category', table_name='prophecies')
    op.drop_table('prophecies')
    op.drop_index('idx_sign_type', table_name='celestial_signs')
    op.drop_index('idx_sign_name', table_name='celestial_signs')
    op.drop_table('celestial_signs')
    # ### end Alembic commands ###
